### ISSUE TITLE
readme description

### ISSUE THREAD

**Issue by scotthosking** [DanJonesOcean/GMM_example#2]
I would suggest making it clear that this example relates to clustering/classification etc and include some plots in the README - a map would be good :-)

I like to use this as an example when people get in touch looking for environmental data

**Comment by DaniJonesOcean** [comment]
Thank you Scott, that's a good suggestion. Apologies for the long delay! I will aim to do this soon.

**Comment by DaniJonesOcean** [comment]
Thanks for the suggestion @scotthosking! I've added a bit more text and an example map to the README.md description. Eventually I should add "Cartopy" and a map-creation feature to this repository. For now, I've left off the map feature, as Cartopy can be difficult to get working sometimes. 

I hope you find the description to be improved!
